### ISSUE TITLE
`mock().using` does not work on method nested inside class property [@automock]

### ISSUE THREAD

**Issue by tsahnar** [suites-dev/suites#328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

We are encountering difficulties when attempting to mock methods that are defined inside existing class properties. The nested property is automatically overwritten with a mocked object, so the actual method inside the property we need to mock is undefined and cannot be accessed (and cannot be mocked, basically).

### Steps to reproduce

1. Define a class with a property that contains a method. e.g.:

```typescript
class OtherClass {
   public  getSomething: () => string
}
```

```typescript
class MyClass {
    readonly property: OtherClass
}
```

2. . Attempt to  mock `MyClass`

```typescript
let myClass:  jest.Mocked<MyClass>;

const { unit, unitRef } = TestBed.create(ServiceUnderTest)
      .mock(MyClass)
      .using({
         property: {
               getSomething: jest.fn()
          }
       })
 .compile();

myClass = unitRef.get(MyClass)
```

3. In the actual test try to mock resolved value getSomething, e.g:

`myClass.property.getSomething.mockResolvedValue('mocked')`

### Expected behavior

The method inside the class property should be successfully mocked. In the above example  trying to do 
`.getSomething.mockResolvedValue` Should not throw an error - getSomething is undefined 

### Automock version

`v2.1.0`

**Comment by omermorad** [comment]
Hello @tsahnar,

Please try the following solution:

```typescript
let myClass:  jest.Mocked<MyClass>;

const propMock = { property: jest.fn() };

const { unit, unitRef } = TestBed.create(ServiceUnderTest)
      .mock(MyClass)
      .using(propMock)
      .compile();

myClass = unitRef.get(MyClass)
```

You can control the mock (`property` stub) from `propMock` const.
