### ISSUE TITLE
reflect-metadata peer dependency conflict in NestJS

### ISSUE THREAD

**Issue by vahidvdn** [suites-dev/suites#541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I want to try to install dependencies as following:

```
npm i -D @suites/unit @suites/di.nestjs @suites/doubles.jest
```

I get the following errors:

```bash
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: ticketing-backend-clients-api@0.0.1
npm error Found: reflect-metadata@0.2.2
npm error node_modules/reflect-metadata
npm error   reflect-metadata@"^0.2.0" from the root project
npm error   peer reflect-metadata@"^0.1.12 || ^0.2.0" from @nestjs/common@10.4.15
npm error   node_modules/@nestjs/common
npm error     @nestjs/common@"^10.0.0" from the root project
npm error     peer @nestjs/common@">= 8.0" from @suites/di.nestjs@3.0.0
npm error     node_modules/@suites/di.nestjs
npm error       dev @suites/di.nestjs@"*" from the root project
npm error
npm error Could not resolve dependency:
npm error peer reflect-metadata@"^0.1.13" from @suites/di.nestjs@3.0.0
npm error node_modules/@suites/di.nestjs
npm error   dev @suites/di.nestjs@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
```

My Nest project is using "reflect-metadata": "^0.2.0"

### Minimum reproduction code

https://github.com/suites-dev/suites

### Steps to reproduce

Install Nestjs version 10, then install the suites deps

### Expected behavior

To get installed

### Node.js version

22.2.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by vahidvdn** [comment]
You have this `peerDependency`:

```
"reflect-metadata": "^0.1.13"
```

On the other Nestjs asks for the following (in the `peerDependency` of `@nestjs/common`):

```
"reflect-metadata": "^0.1.12 || ^0.2.0",
```

But, NestJS installs this automatically in the root project:

```
"reflect-metadata": "^0.2.0",
```

So, one solution is downgrading my reflect-metadata to  `"^0.1.13"`, but it's not the best idea. I guess you can simply do:

```
"reflect-metadata": "^0.1.12 || ^0.2.0",
```

Or if `0.1.12` is too old, this also work:

```
"reflect-metadata": "^0.1.13 || ^0.2.0",
```

**Comment by omermorad** [comment]
Relates to #461

**Comment by vahidvdn** [comment]
@omermorad Sorry, but it doesn't work for me. I am installing the latest version, but I still get that error.

**Comment by omermorad** [comment]
@vahidvdn what version do you use?

**Comment by vahidvdn** [comment]
@omermorad oh, sorry, you've released last day. Now it works fine, thank you

**Comment by omermorad** [comment]
Awesome!
